# -*- coding: utf-8 -*-
"""titanic streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DYBx2gcFudNeD-5PP6MM531XpzN-o9vN
"""

import streamlit as st
import joblib as jb
import numpy as np
import pandas as pd
import sklearn 

model = jb.load("titanic_model.pkl")

st.title(" titanic project ")
st.write("ادخل البيانات لمعرفة اذا كان سينجو ام لا ")

Pclass = st.selectbox("passenger class: " , [1,2,3])
Age = st.number_input("Age", min_value=0, max_value=100)
SibSp = st.number_input("SibSp", min_value=0, max_value=10)
Parch = st.number_input("Parch", min_value=0, max_value=10)
Fare = st.number_input("Fare", min_value=0,)

Sex =  st.selectbox("gender " , ["male" , " female"])
Embarked =  st.selectbox("Embarked " , ["S" , "C" ,"Q"])


if st.button("تنبا الان "):
  input_dir ={"Pclass" : [Pclass],
              "Sex" :[Sex],
              "Age" :[Age],
              "SibSp" :[SibSp],
              "Parch" :[Parch],
              "Fare" :[Fare],
              "Embarked" : [Embarked]}

  input_df = pd.DataFrame(input_dir)
  input_df = pd.get_dummies(input_df, columns = ["Sex" , "Embarked"])

  model_col = model.feature_name_in

  for i in model_col :
    if i not in input_df.columns:
      input_df[i] = 0

  input_df = input_df[model_col]

  prediction = model.predict(input_df)


  if prediction[0] == 1:
    st.success("الراكب نجا ")
  else:
    st.error("الراكب لم ينجو ")
